name: setup-node

runs:
  using: composite

  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        cache: "npm"
        node-version: "22.13.0"

    - name: Install dependencies
      run: npm ci
