global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "weather-app-dev"
    static_configs:
      - targets: ["host.docker.internal:3000"]
    scrape_interval: 5s
    metrics_path: /api/metrics

  - job_name: "weather-app-prod"
    static_configs:
      - targets: ["api:3000"]
    scrape_interval: 5s
    metrics_path: /api/metrics
