name: build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and dependencies
        uses: ./.github/actions/setup-node

      - name: Run build
        run: npm run build
