name: lint

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and dependencies
        uses: .github/actions/setup-node

      - name: Run lint
        run: npm run lint
