name: e2e-test

on:
  workflow_dispatch:
  push:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services
        run: docker compose up -d

      - name: Set up Node.js and dependencies
        uses: ./.github/actions/setup-node

      - name: Run E2e Tests
        run: npm run test:e2e
