name: arch-test

on:
  workflow_dispatch:
  push:

jobs:
  arch-test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and dependencies
        uses: ./.github/actions/setup-node

      - name: Run Architecture Tests
        run: npm run test:arch

      - name: Run Deps Tests
        run: npm run test:deps
