name: integration-test

on:
  workflow_dispatch:
  push:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Start services
        run: docker compose up -d

      - name: Set up Node.js and dependencies
        uses: ./.github/actions/setup-node

      - name: Run Integration Tests
        run: npm run test:integration
