name: test

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and dependencies
        uses: ./.github/actions/setup-node

      - name: Start services
        run: docker compose up -d pg

      - name: Run Test
        run: npm run test
